[package]
name = "mini_tiger_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "lexer"
path = "src/lexer.rs"
[dependencies]
anyhow = "1.0.59"
thiserror = "1.0.31"